backend:
  name: git-gateway
  repo: chrisvanmook/gatsby-netlify-cms
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'layers'
    label: 'Layers'
    folder: 'content/layers'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
  - name: 'collection'
    label: 'Collection (Themes)'
    folder: 'content/collection'
    create: true
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - label: 'Layers',
        name: "layers"
        widget: "relation"
        collection: "layers"
        search_fields: [ "title" ]
        value_field: "title"
        display_fields: [ "title" ]
